### ISSUE TITLE
[Bug] in iOS 14 await Permissions.RequestAsync<Permissions.LocationXXX>() does not return after the pop-up is closed

### ISSUE THREAD

**Issue by gsgou** [xamarin/Essentials#1390]
### Current Behavior

in iOS 14 when permission is accepted and right after the pop-up is closed
await Permissions.RequestAsync<Permissions.LocationWhenInUse>(); or
await Permissions.RequestAsync<Permissions.LocationAlways>();
never returns, or throws an exception the first time called.

### Expected Behavior

in iOS 14 when permission is accepted and right after the pop-up is closed
await Permissions.RequestAsync<Permissions.LocationWhenInUse>(); or
await Permissions.RequestAsync<Permissions.LocationAlways>();
returns  PermissionStatus.Granted.

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: not known
- IDE: Visual Studio for Mac 8.7.8 (build 4)
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS 14.0.0.0
- Affected Devices: Simulator iPhone 11, iOS 14.0

**Comment by gsgou** [comment]
Closing it as on the Sample works. Must be an issue executing the async function with ReactiveUI or another issue that needs investigation.

**Comment by gurfing** [comment]
Same for me.
Currently use this workaround:
```
while (true)
                {
                    if (await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>() == PermissionStatus.Granted)
                        break;

                    Permissions.RequestAsync<Permissions.LocationWhenInUse>();

                    await Task.Delay(1000);
                }
```

**Comment by Tommigun1980** [comment]
Was just about to report this.

Is there an ETA on a fix? iOS 14 is already out.

Thanks.

**Comment by Fammy** [comment]
I dug in some and the `CLLocationManager.AuthorizationChanged` event does not appear to be called after permission is granted (or denied).

Interestingly, the CLLocationManagerDelegate.AuthorizationChanged` method does get called if I use the delegate pattern instead (at least in my rudimentary re-implementation I experimented with).

I am leaning towards this being an issue in Xamarin.iOS proper or possibly iOS, but who knows 🤷‍♂️ 

The [PermissionsPlugin](https://github.com/jamesmontemagno/PermissionsPlugin) also has this issue.

**Comment by Tommigun1980** [comment]
> I dug in some and the `CLLocationManager.AuthorizationChanged` event does not appear to be called after permission is granted (or denied).
> 
> Interestingly, the CLLocationManagerDelegate.AuthorizationChanged` method does get called if I use the delegate pattern instead (at least in my rudimentary re-implementation I experimented with).
> 
> I am leaning towards this being an issue in Xamarin.iOS proper or possibly iOS, but who knows 🤷‍♂️
> 
> The [PermissionsPlugin](https://github.com/jamesmontemagno/PermissionsPlugin) also has this issue.

Thanks for the research. Do you think the best course of action would be to report it a bug to Xamarin.iOS so they can have a look at it, or do you think the plugin should be rewritten to use the delegate pattern instead?

**Comment by Tommigun1980** [comment]
> Same for me.
> Currently use this workaround:
> 
> ```
> while (true)
>                 {
>                     if (await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>() == PermissionStatus.Granted)
>                         break;
> 
>                     Permissions.RequestAsync<Permissions.LocationWhenInUse>();
> 
>                     await Task.Delay(1000);
>                 }
> ```

I think something like this would be better:

```c#
                Permissions.RequestAsync<TPermission>();
                while (await Permissions.CheckStatusAsync<TPermission>() == PermissionStatus.Unknown)
                    await Task.Delay(50);
                return await Permissions.CheckStatusAsync<TPermission>();
```

**Comment by mduchev** [comment]
Yep, same here.

**Comment by jamesmontemagno** [comment]
Need to debug through this one, i have seen this on my other one. Apparently in iOS 14 they have changed the callbacks :(

**Comment by mattleibow** [comment]
Maybe there is some new api that ios 14 expects you to use? How would you do this in objc/swift?

**Comment by Mustafa-ah** [comment]
I have temporary solved my problem with this code

`public class PermissionService : IPermissionService
    {
        public PermissionService()
        {
        }
        LocationCheck showTrackingMap;
        public async Task<PermissionStatus> RequestPermissionsAsync()
        {
            PermissionStatus permission = PermissionStatus.Unknown;
            showTrackingMap = new LocationCheck((s, ev) =>
            {
                if ((ev as LocationCheck.LocationCheckEventArgs).Allowed)
                {
                    permission = PermissionStatus.Granted;
                }
                else
                {
                    permission = PermissionStatus.Denied;
                }

                showTrackingMap.Dispose();
            });

            while (permission == PermissionStatus.Unknown)
            {
                await Task.Delay(10);
            }

            return permission;
        }
    }

    public class LocationCheck : NSObject, ICLLocationManagerDelegate
    {
        public class LocationCheckEventArgs : EventArgs
        {
            public readonly bool Allowed;
            public LocationCheckEventArgs(bool Allowed)
            {
                this.Allowed = Allowed;
            }
        }

        CLLocationManager locationManager;
        EventHandler locationStatus;

        public LocationCheck(EventHandler locationStatus)
        {
            this.locationStatus = locationStatus;
            Initialize();
        }

        public LocationCheck(NSObjectFlag x) : base(x) { Initialize(); }

        public LocationCheck(IntPtr handle) : base(handle) { Initialize(); }

        public LocationCheck(IntPtr handle, bool alloced) : base(handle, alloced) { Initialize(); }

        public void Initialize()
        {
            locationManager = new CLLocationManager
            {
                Delegate = this
            };
            locationManager.RequestAlwaysAuthorization();
        }

        [Export("locationManager:didChangeAuthorizationStatus:")]
        public void AuthorizationChanged(CLLocationManager manager, CLAuthorizationStatus status)
        {
            switch (status)
            {
                case CLAuthorizationStatus.AuthorizedAlways:
                case CLAuthorizationStatus.AuthorizedWhenInUse:
                    locationStatus.Invoke(locationManager, new LocationCheckEventArgs(true));
                    break;
                case CLAuthorizationStatus.Denied:
                case CLAuthorizationStatus.Restricted:
                    locationStatus.Invoke(locationManager, new LocationCheckEventArgs(false));
                    break;
            }
        }

        protected override void Dispose(bool disposing)
        {
            locationStatus = null;
            locationManager.Delegate = null;
            locationManager.Dispose();
            base.Dispose(disposing);
        }
    }`

**Comment by StefAnglr** [comment]
Here's my workaround. I wasn't seeing `CLLocationManagerDelegate.AuthorizationChanged` in my own implementation, whether I subclass the base `CLLocationManagerDelegate` like this, or implement `ICLLocationManagerDelegate` with an Export like @Mustafa-ah, so I'm falling back to polling if it's never called.

```
    public class LocationPermissionService : CLLocationManagerDelegate
    {
        private TaskCompletionSource<PermissionStatus> _tcs;
        private CLLocationManager _manager;

        public LocationPermissionService(CLLocationManager manager)
        {
            _manager = manager ?? throw new ArgumentNullException(nameof(manager));
            _manager.Delegate = this;
        }

        public override void AuthorizationChanged(CLLocationManager manager, CLAuthorizationStatus status)
        {
            // This doesn't seem to be called.
            _tcs?.TrySetResult(ToPermissionStatus(status));
        }

        public async Task<PermissionStatus> RequestAlwaysPermission(CancellationToken cancelToken = default)
        {
            if (!CLLocationManager.LocationServicesEnabled) return PermissionStatus.Disabled;
            if (CLLocationManager.Status != CLAuthorizationStatus.NotDetermined) return ToPermissionStatus(CLLocationManager.Status);

            _tcs = new TaskCompletionSource<PermissionStatus>();
            _manager.RequestAlwaysAuthorization();
            // Due to iOS bug, we have to poll for the status. Cool!
            // Let's poll every half second for 10 seconds, and also await the callback just in case it works
            var delegateTask = _tcs.Task.WaitAsync(cancelToken);
            for (int i = 0; i < 20; i++)
            {
                var delayTask = Task.Delay(500, cancelToken);
                var awaitedTask = await Task.WhenAny(delegateTask, delayTask);
                if (awaitedTask == delegateTask)
                {
                    return await delegateTask;
                }
                else if (CLLocationManager.Status != CLAuthorizationStatus.NotDetermined)
                {
                    return ToPermissionStatus(CLLocationManager.Status);
                }
            }
            // Timed out or maybe the prompt was dismissed, just return what we know
            return ToPermissionStatus(CLLocationManager.Status);
        }

        public PermissionStatus GetPermissionStatus(CancellationToken cancelToken = default)
        {
            if (!CLLocationManager.LocationServicesEnabled) return PermissionStatus.Disabled;
            return ToPermissionStatus(CLLocationManager.Status);
        }

        private PermissionStatus ToPermissionStatus(CLAuthorizationStatus status) => status switch
        {
            CLAuthorizationStatus.AuthorizedAlways => PermissionStatus.Granted,
            CLAuthorizationStatus.AuthorizedWhenInUse => PermissionStatus.Granted,
            CLAuthorizationStatus.Denied => PermissionStatus.Denied,
            CLAuthorizationStatus.NotDetermined => PermissionStatus.Unknown,
            CLAuthorizationStatus.Restricted => PermissionStatus.Denied,
            _ => PermissionStatus.Unknown
        };
    }
```

**Comment by msjogren** [comment]
@StefAnglr `CLLocationManagerDelegate.AuthorizationChanged` is deprecated as of iOS 14, but it's replaced by `CLLocationManagerDelegate.DidChangeAuthorization`. For me that seems to be called reliably, so no polling needed. Of course you need to handle both to support iOS < 14 too.

**Comment by aherrick** [comment]
What I'm seeing is when requesting location, on iOS 14 the "Allow Location" prompt is show very briefly, then it instantly goes away before I'm able to click "Use location while in App" 

Is this issue related? Below is my simple code.

```
     while (true)
                {
                    if (await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>() == PermissionStatus.Granted)
                       break;

                    await AppHelper.RequestAsync_Fixed<Permissions.LocationWhenInUse>();
                }

                var request = new GeolocationRequest(GeolocationAccuracy.Medium)
                {
                    Timeout = TimeSpan.FromSeconds(30)
                };

                var location = await Geolocation.GetLocationAsync(request);

```

**Comment by mattleibow** [comment]
@msjogren has done the work to resolve this and I will try get a preview out as soon as possible.

**Comment by mattleibow** [comment]
You can test the fix in the nuget from the artifacts here:
https://dev.azure.com/xamarin/public/_build/results?buildId=30010&view=results

**Comment by RomanNakonechnyi** [comment]
Is there any way to determine if location is granted as "precise" or not? And second question whether it is planned at all to be in xamarin.essentials?

**Comment by mattleibow** [comment]
@RomanNakonechnyi could you open a new issue with that?

**Comment by RomanNakonechnyi** [comment]
> @RomanNakonechnyi could you open a new issue with that?

https://github.com/xamarin/Essentials/issues/1523 here it is. Please, confirm if it makes sense.

**Comment by anders9ustafsson** [comment]
Not sure if this issue has been sufficiently fixed? I have tried to upgrade from 1.5.3.2 to Essentials 1.6.1, and I programmatically request permissions for mic, camera, location and push notifications. Permissions are correctly requested, but the status of the push notifications request, which appears after location, is incorrectly *not granted*. If I on the other hand maintain the workaround suggested [above](https://github.com/xamarin/Essentials/issues/1390#issuecomment-698000677), all permission statuses are correct.

**Comment by mduchev** [comment]
@anders9ustafsson I haven't looked through the commits for this fix but as far as I know, the original issue with the location is fixed. 

I can suggest you to create a new issue and attach a sample project to it.

**Comment by hvaughan3** [comment]
I can confirm, updating to Essentials 1.6.1 fixed the location permission request issue for me.

**Comment by anders9ustafsson** [comment]
Realize I was not entirely clear. Yes, the location issue itself appears to have been fixed for me as well, but it seems like there is a lingering issue when requesting further permissions, after having called the location permission. This lingering issue is not present when using the referenced workaround, so I am concerned the bug fix included in 1.6.x is not complete.

If I have the opportunity, I will try to create a test project that highlights my concern in isolation.

**Comment by sisaacks** [comment]
I can confirm that 1.6.1 I still have permission issues when calling from a popup.  The call never returns...on IOS 14 Iphone 11....so basically the same bug the guy reported

**Comment by sisaacks** [comment]
@hvaughan3 I still have the issue....I call to request permissions and I never get a callback....I have updated to all the latest

**Comment by sisaacks** [comment]
@mattleibow i see you closed this issue but I am still seeing it on IOS 14 Iphone 11.

**Comment by sisaacks** [comment]
@gsgou How come this is closed?  I am still seeing this issue that you reported

**Comment by mattleibow** [comment]
@sisaacks which permission are you requesting? Have you updated to 1.6.1?

**Comment by mattleibow** [comment]
@anders9ustafsson which permission did you notice this on? I'll go and review them all again, but it will help to verify the one that you see failing.

**Comment by sisaacks** [comment]
@mattleibow I realized after I posted this that I am using @jamesmontemagno Plugin Permissions, so maybe that has not been updated???
This is the call I am using: await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();
When I receive the system popup and select "Allow" or any option really....nothing is ever returned from this method. 
If I then click the button again, and I have previously selected "Allow", then everything works fine.

**Comment by sisaacks** [comment]
@mattleibow sorry I hit the wrong copy paste 
this is the call I am using
await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();

**Comment by sisaacks** [comment]
@mattleibow for some reason its not showing up....LocationPermission is what I am calling

**Comment by sisaacks** [comment]
@mattleibow I am not sure if you know the answer or not.  I have submitted on Plugin Permission Github as well.  Any assistance would be greatly appreciated

**Comment by gsgou** [comment]
@sisaacks probably the quickest would be to use with the Plugin Permissions
a similar workaround as this:
https://github.com/xamarin/Essentials/issues/1390#issuecomment-698000677
or simply move to Xamarin.Essentials which is better supported.

**Comment by mattleibow** [comment]
The correct solution is to use essentials 😉

**Comment by sisaacks** [comment]
@gsgou I tired but it did not work

**Comment by mduchev** [comment]
@sisaacks What have you tried exactly?

**Comment by sisaacks** [comment]
The solution above but changed to use Plugin Permissions

**Comment by alzubitariq** [comment]
Closed !!!! the same issue with iOS 14.4

**Comment by mannam95** [comment]
I have upgraded from 1.5.3.2 to Essentials 1.6.1 and the iPhone version is 14.6. 
I can confirm that the issue is still there. where that application has location permissions but when it hits the following call it never returns and the app is stuck.
 ```
public async Task<Location> GetLocation()
        {
                var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));

                return await Geolocation.GetLocationAsync(request);
        }
```

@mattleibow Can you check about this, because we couldn't deploy our application in the AppStore for 5 months

**Comment by alzubitariq** [comment]
@mannam95 
Are you using emulator or real device ? 
if it is an emulator make sure to run GPS services before asking for location

**Comment by mannam95** [comment]
@alzubitariq I am using a real device

**Comment by alzubitariq** [comment]
@mannam95 
The permission is something and getting location is something different 
You have to have a permission first of all and it simple to ask for it , but please make sure "Location Services Enabled" for your "app" 
put this line inside the (AppDelegate => FinishedLaunching) with some break points and see the results 
var isEnabled = CoreLocation.CLLocationManager.LocationServicesEnabled;

**Comment by mannam95** [comment]
@alzubitariq I did try the way how you asked me to do so, The variable is having true in it, So the issue is with the above function which I had mentioned and also I feel if permissions aren't there then I would expect it to throw exception not to stuck forever.

**Comment by alzubitariq** [comment]
@mannam95 
You are telling there is a deadlock like your are not awaiting your task , are you calling the method synchronously ! ,,, please try again inside (AppDelegate => FinishedLaunching) 
var hasPermission  = CoreLocation.CLLocationManager.Status == CoreLocation.CLAuthorizationStatus.AuthorizedAlways || CoreLocation.CLLocationManager.Status == CoreLocation.CLAuthorizationStatus.AuthorizedWhenInUse;

and go to app settings inside your phone , check location services is enabled for your app manually

**Comment by mannam95** [comment]
I went to the app setting and can see that location permissions are enabled. 

Secondly, on the launch of the app, I am not trying to check the location permissions. I am trying to get the location details on click of the button inside the app

```
//This is an async function
public async Task<Location> GetLocation()
       {
               var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));

               return await Geolocation.GetLocationAsync(request);
       }

//In another function where I am calling this async func, I wait for the response like below
Task.Run(async () => { await this.GetLocation(); }).Wait();

```

So I wait for the response in which it never returns.

**Comment by alzubitariq** [comment]
I think you are blocking the UI thread , if the async method awaits something that requires an UI event to complete then you will have deadlock even with the nested context, in this case you have to start the async method on the thread pool
try to with this way 

return await Geolocation.GetLocationAsync(request).ConfigureAwait(false);

**Comment by alzubitariq** [comment]
and one more thing why you are using async in GetLocation method ? there is no need to put here and there , it is much more expensive on ram , you can keep your method like this 
public Task<Location> GetLocation()
{
       var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));
       return Geolocation.GetLocationAsync(request);
}

**Comment by mannam95** [comment]
> I think you are blocking the UI thread , if the async method awaits something that requires an UI event to complete then you will have deadlock even with the nested context, in this case you have to start the async method on the thread pool
> try to with this way
> 
> return await Geolocation.GetLocationAsync(request).ConfigureAwait(false);

@alzubitariq I tried this but it doesn't work

**Comment by mannam95** [comment]
> and one more thing why you are using async in GetLocation method ? there is no need to put here and there , it is much more expensive on ram , you can keep your method like this
> public Task GetLocation()
> {
> var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));
> return Geolocation.GetLocationAsync(request);
> }

@alzubitariq  The code which is exactly happening on button click is something like below

```
//Class A
//On button click

private void onAddButtonClicked()
{
  //do somethings
  
  Task.Run(async () => { await this.GetLocation(); }).Wait();
  
  //do dome other things once location is returned
}


private async Task GetLocation()
{
	Location locOfDevice = null;
	try
	{
		LocationManager locMan = new LocationManager();
		locOfDevice = await locMan.GetLocation();
	}
	catch (FeatureNotSupportedException fnsex)
	{
		this._displayNoGPSAvailable = true;
	}
	catch (FeatureNotEnabledException fneex)
	{
		this._displayNoGPSAvailable = true;
	}
	catch (PermissionException pex)
	{
		this._displayAppHasNoGPSPermissions = true;
	}
	catch (Exception ex)
	{
		Console.WriteLine($"Error is: { ex.Message }");
	}

	this._currentDeviceLocation = locOfDevice;
}

//End of Class A


// LocationManager Class

 public async Task<Location> GetLocation()
{
	GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromMilliseconds(1));

	return await Geolocation.GetLocationAsync(request);
}
```
Where on onAddButtonClicked method fires when the respected button is clicked in the mobile app. It calls a method called GetLocation and waits for it to complete. once it completes then it means the location variable should have been updated. The same logic works perfectly in android and doesn't work only in IOS. 

Please let me know if there is some problem.
