### ISSUE TITLE
[Bug] Can no longer build Android targets with Linking

### ISSUE THREAD

**Issue by queequac** [xamarin/Essentials#1850]
After upgrading to version 1.7, I am no longer able to create a release build or to archive my Android project, because I am using the linking option for "SDK and user assemblies" there.
While version 1.6.1 works just fine, build fails due to the following error message when having the option mentioned above enabled:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void AndroidX.RecyclerView.Widget.RecyclerView/LayoutManager::n_OnInitializeAccessibilityNodeInfo_Landroidx_recyclerview_widget_RecyclerView_Recycler_Landroidx_recyclerview_widget_RecyclerView_State_Landroidx_core_view_accessibility_AccessibilityNodeInfoCompat_(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)' in assembly: 'Xamarin.AndroidX.RecyclerView.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Core.View.Accessibiity.AccessibilityNodeInfoCompat
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    --- End of inner exception stack trace ---
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Mono.Linker.Pipeline.Process(LinkContext context)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): error XALNK7000:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17

```

### Description

I can trigger that error by enabling "SDK and user assemblies" for linking and I can build when turning that option off (setting it to "none").
As a current workarround I downgrade to 1.6.1 again.

### Steps to Reproduce

1. Upgrade Xamarin.Essentials via Nuget to 1.7
2. Activate linking.
3. Build 

### Expected Behavior

The project should compile and link without any errors just like with 1.6.1

### Actual Behavior

The above error message is generated and build fails.

### Basic Information

- Version with issue: 1.7
- Last known good version: 1.6.1
- IDE: Visual Studio 2019 16.10.3
- Platform Target Frameworks: 
  - Android SDK: 11.3.0.4

**Comment by jamesmontemagno** [comment]
What version of Xamarin.Forms are you using and what version of the RecyclerView nuget do you have?

**Comment by queequac** [comment]
@jamesmontemagno I am not using Xamarin.Forms, just plain Xamarin.Android.
And I do not use any ReclyerView directly... maybe that's a dependency that comes with Uno platform?🤔 Using latest version of Uno (Uno.Ui, 3.8.13)

**Comment by jamesmontemagno** [comment]
So the Uno team will need to bump their dependencies. Right now they are building with Xamarin.AndroidX.AppCompat 1.1.0 which depends on Xamarin.AndroidX.Core 1.1.0. These dependencies need to be bumped as there was an issue in older 1.1.0 with an accessbility namespace that had a typo and this was fixed in Xamarin.AndroidX.Core 1.3.2.2.

They will need to bump their Xamarin.AndroidX.AppCompat dependency atleast to 1.2.0.7. I would open an issue with Uno

**Comment by queequac** [comment]
I will open an issue there... just wondering why it builds without any warnings when using Xamarin.Essentials 1.6.1 then... 🤔

**Comment by queequac** [comment]
But shouldn't the issue be resolved then by explicitly adding Xamarin.AndroidX.AppCompat 1.2.0.7 or higher to my project (since Uno depends on >= 1.1)? In this case the linker error remains the same.

**Comment by queequac** [comment]
Ah, also adding Xamarin.AndroidX.RecyclerView with latest 1.2.1 and the issue is gone. So definitely an issue with old dependencies on Uno.UI.
Thanks for the hint!

**Comment by jamesmontemagno** [comment]
Glad that it is working now :) yeah they probably don't use any of the accessibility apis so that is good to know. Can you open an issue over on the Uno side? I am sure they will do a bump to align.

**Comment by jeromelaban** [comment]
@jamesmontemagno thanks for the help! 

We generally don't force update the dependencies for single android SDKs transitively, as it makes the linkers (.NET or Java) generally quite unhappy. This happens (regardless of this specific naming issue) because underlying java binaries may be incompatible with each other... We generally prefer that developers upgrade packages on their end so that the AndroidX packages graph works for their case.

We'll certainly do update for `monoandroid12.0` if this is a target framework that will happen for X.A, or for `net6.0-android30` or `net6.0-android31`.

**Comment by jamesmontemagno** [comment]
@jeromelaban totally understand where you are coming from. The issue here lies with a typo that causes break AndroidX.Core.View.Accessibiity to AndroidX.Core.View.Acessibility -> http://fuget.org/packages/Xamarin.AndroidX.Core/1.3.2.2/lib/monoandroid90/diff/1.3.2.1/

Newer and updated libraries that take a dependency on any library that has a dependency and built against Xamarin.AndroidX.Core 1.3.2.2 and newer will cause this break in Uno.UI. This will ever increase as Xamarin.Forms, Xamarin.Esssentials, Xamarin Community Toolkit, and any library using firebase will have these breaks as well.

I would maybe take a look at the minimums that Xamarin.Forms takes -> https://www.nuget.org/packages/Xamarin.Forms/

Android compat libraries are the worse and always need constant shifting unfortunately. It looks like your net6.0-android30 does take the newer libs so should be good there, but I may look into bumping a few things or documenting this on your side. Tricky one, always open to chat more, you have my email :)
